main: ct.ChatManagerPlus.Main
version: 1.1.2
name: ChatManagerPlus
author: CyranoTrinity

commands:
    chatmanagerplus:
        description: ChatManagerPlus commands
        aliases: [cmp]
    lockchat:
        description: Lock global chat
    unlockchat:
        description: Unlock global chat
    clearchat:
        description: Clear chat
    mute:
        description: Mute player
    unmute:
        description: Unmute player
    staffchat:
        description: Chat for Staff
        aliases: [sc]
    cbroadcast:
        description: Broadcast
        aliases: [cbc]
    chatcooldown:
        description: Chat Cooldown
permissions:
    ChatManagerPlus.*:
        description: Gives access to all ChatManagerPlus commands
        children:
            ChatManagerPlus.lockchat: true
            ChatManagerPlus.clearchat: true
            ChatManagerPlus.mute: true
            ChatManagerPlus.staffchat: true
            ChatManagerPlus.cooldownchat: true
            ChatManagerPlus.broadcast: true
    ChatManagerPlus.lockchat:
        description: Disable/Enable global chat
        default: false
    ChatManagerPlus.clearchat:
        description: Clear chat
        default: false
    ChatManagerPlus.mute:
        description: Mute player or all
        default: false
    ChatManagerPlus.staffchat:
        description: Staff Chat
        default: false
    ChatManagerPlus.cooldownchat:
        description: Chat cooldown
        default: false
    ChatManagerPlus.broadcast:
        description: Broadcast
        default: false